-- doing this first so other plugins pick up the colorscheme
require('plugins.config.onedark')
require('plugins.config.telescope')
require('plugins.config.auto-save')
require('plugins.config.bufferline')
require('plugins.config.lualine')
require('plugins.config.nvim-cmp')
require('plugins.config.nvim-scrollbar')
require('plugins.config.nvim-tree')
require('plugins.config.lsp')
require('plugins.config.treesitter')
require('plugins.config.autopairs')
