-- doing this first so other plugins pick up the colorscheme
require('plugins.config.colorscheme')
require('plugins.config.lsp')
require('plugins.config.telescope')
require('plugins.config.dressing')
require('plugins.config.auto-save')
require('plugins.config.notify')
require('plugins.config.auto-session')
require('plugins.config.comment')
require('plugins.config.lualine')
require('plugins.config.live-command')
require('plugins.config.nvim-cmp')
require('plugins.config.dap')
require('plugins.config.nvim-scrollbar')
require('plugins.config.nvim-tree')
require('plugins.config.treesitter')
require('plugins.config.autopairs')
require('plugins.config.toggleterm')
require('plugins.config.nvim-surround')
require('plugins.config.luasnip')
require('plugins.config.nvim-lightbulb')
require('plugins.config.marks')
require('plugins.config.legendary')
require('plugins.config.spectre')
require('plugins.config.wilder')
require('plugins.config.colorizer')

vim.g.blamer_date_format = '%m/%d/%y'
