-- doing this first so other plugins pick up the colorscheme
require('config.plugins.colorscheme')
require('config.plugins.lsp')
require('config.plugins.telescope')
require('config.plugins.dressing')
require('config.plugins.auto-save')
require('config.plugins.notify')
require('config.plugins.auto-session')
require('config.plugins.comment')
require('config.plugins.lualine')
require('config.plugins.live-command')
require('config.plugins.nvim-cmp')
require('config.plugins.dap')
require('config.plugins.nvim-scrollbar')
require('config.plugins.nvim-tree')
require('config.plugins.treesitter')
require('config.plugins.autopairs')
require('config.plugins.toggleterm')
require('config.plugins.nvim-surround')
require('config.plugins.luasnip')
require('config.plugins.nvim-lightbulb')
require('config.plugins.marks')
require('config.plugins.legendary')
require('config.plugins.spectre')
require('config.plugins.wilder')
require('config.plugins.colorizer')

vim.g.blamer_date_format = '%m/%d/%y'
