-- doing this first so other plugins pick up the colorscheme
require('plugins.colorscheme')
require('plugins.lsp')
require('plugins.telescope')
require('plugins.dressing')
require('plugins.auto-save')
require('plugins.notify')
require('plugins.auto-session')
require('plugins.comment')
require('plugins.lualine')
require('plugins.live-command')
require('plugins.nvim-cmp')
require('plugins.dap')
require('plugins.nvim-scrollbar')
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.autopairs')
require('plugins.toggleterm')
require('plugins.nvim-surround')
-- require('plugins.luasnip')
require('plugins.nvim-lightbulb')
require('plugins.marks')
require('plugins.legendary')
require('plugins.spectre')
require('plugins.wilder')
require('plugins.colorizer')

vim.g.blamer_date_format = '%m/%d/%y'
